# 特征值预处理

### VarianceThreshold

In [1]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold

X = np.array([
    [0, 2, 0, 3],
    [0, 1, 4, 3],
    [0, 1, 1, 3]
])

# 实例化 VarianceThreshold，默认 threshold=0，去除零方差特征（方差为0的列）
sel = VarianceThreshold(threshold=0.5)
X_new = sel.fit_transform(X)

print("原始特征矩阵：\n", X)
print("去除低方差后的特征矩阵：\n", X_new)

# 输出剩余特征列的索引
retained_indices = sel.get_support(indices=True)
print("剩余特征的列索引：", retained_indices)

原始特征矩阵：
 [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]
去除低方差后的特征矩阵：
 [[0]
 [4]
 [1]]
剩余特征的列索引： [2]


### PCA

In [2]:
from sklearn.decomposition import PCA

X = np.array([
    [0, 2, 0, 3],
    [0, 1, 4, 3],
    [0, 1, 1, 3]
])

# 使用PCA进行降维，降到2维
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("原始特征矩阵：\n", X)
print("PCA降维后的特征矩阵：\n", X_pca)
print("各主成分的方差解释比例：", pca.explained_variance_ratio_)

原始特征矩阵：
 [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]
PCA降维后的特征矩阵：
 [[-1.76504522  0.32686023]
 [ 2.35339362  0.13074409]
 [-0.58834841 -0.45760432]]
各主成分的方差解释比例： [0.96428571 0.03571429]
