# ndarray

## 一维

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [7]:
# 常用的ndarray属性和方法示例：

# 形状（shape）
print("a.shape:", a.shape)      # 输出：(5,)

# 数据类型（dtype）
print("a.dtype:", a.dtype)      # 元素类型，通常为 int32/int64/float32 等

# 元素个数（size）
print("a.size:", a.size)        # 输出元素总数：5

# 维度数量（ndim）
print("a.ndim:", a.ndim)        # 输出数组的维数：1

# 转置（T）
print("a.T:", a.T)              # 一维数组转置还是自身

# 改变形状（reshape）
a_reshaped = a.reshape((5, 1))
print("a.reshape((5,1)):\n", a_reshaped)

# 将ndarray转为python list
a_list = a.tolist()
print("a.tolist():", a_list)

# 由python list转为ndarray
b = np.array(a_list)
print("np.array(a_list):", b)

# 最大值、最小值、均值等常用方法
print("a.max():", a.max())
print("a.min():", a.min())
print("a.mean():", a.mean())

a.shape: (5,)
a.dtype: int64
a.size: 5
a.ndim: 1
a.T: [1 2 3 4 5]
a.reshape((5,1)):
 [[1]
 [2]
 [3]
 [4]
 [5]]
a.tolist(): [1, 2, 3, 4, 5]
np.array(a_list): [1 2 3 4 5]
a.max(): 5
a.min(): 1
a.mean(): 3.0


## 二维

In [8]:
# 创建一个二维ndarray
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("arr2d:\n", arr2d)

# 常用属性
print("arr2d.shape:", arr2d.shape)      # 输出：(2, 3)
print("arr2d.dtype:", arr2d.dtype)      # 元素类型，如 int32/int64
print("arr2d.size:", arr2d.size)        # 元素总数：6
print("arr2d.ndim:", arr2d.ndim)        # 维数：2

# 转置
print("arr2d.T:\n", arr2d.T)

# 改变形状（reshape）
arr2d_reshaped = arr2d.reshape((3, 2))
print("arr2d.reshape((3,2)):\n", arr2d_reshaped)

# 转为python list
arr2d_list = arr2d.tolist()
print("arr2d.tolist():", arr2d_list)

# 由python list转为ndarray
arr2d_from_list = np.array(arr2d_list)
print("np.array(arr2d_list):\n", arr2d_from_list)

# 最大值、最小值、均值等
print("arr2d.max():", arr2d.max())
print("arr2d.min():", arr2d.min())
print("arr2d.mean():", arr2d.mean())

arr2d:
 [[1 2 3]
 [4 5 6]]
arr2d.shape: (2, 3)
arr2d.dtype: int64
arr2d.size: 6
arr2d.ndim: 2
arr2d.T:
 [[1 4]
 [2 5]
 [3 6]]
arr2d.reshape((3,2)):
 [[1 2]
 [3 4]
 [5 6]]
arr2d.tolist(): [[1, 2, 3], [4, 5, 6]]
np.array(arr2d_list):
 [[1 2 3]
 [4 5 6]]
arr2d.max(): 6
arr2d.min(): 1
arr2d.mean(): 3.5
