### 完成数组的添加练习

In [1]:
import numpy as np

arr = np.random.rand(2, 3)
print(arr)

[[0.05901897 0.56723417 0.88788037]
 [0.43439187 0.69251217 0.53987133]]


In [3]:
# append案例：展示np.append的三种用法

new_row = np.array([[1, 2, 3]])
new_col = np.array([[1], [2]])  # 为按axis=1追加准备的新列

# 1. 默认append（不指定axis，数组会被拉平成一维后拼接）
arr_appended_default = np.append(arr, new_row)
print("默认append（不指定axis）后的数组：")
print(arr_appended_default)

# 2. 按axis=0追加一行（纵向拼接，即增加行）
arr_appended_axis0 = np.append(arr, new_row, axis=0)
print("\n按axis=0追加一行后的数组：")
print(arr_appended_axis0)

# 3. 按axis=1追加一列（横向拼接，即增加列）
arr_appended_axis1 = np.append(arr, new_col, axis=1)
print("\n按axis=1追加一列后的数组：")
print(arr_appended_axis1)

默认append（不指定axis）后的数组：
[0.05901897 0.56723417 0.88788037 0.43439187 0.69251217 0.53987133
 1.         2.         3.        ]

按axis=0追加一行后的数组：
[[0.05901897 0.56723417 0.88788037]
 [0.43439187 0.69251217 0.53987133]
 [1.         2.         3.        ]]

按axis=1追加一列后的数组：
[[0.05901897 0.56723417 0.88788037 1.        ]
 [0.43439187 0.69251217 0.53987133 2.        ]]
