### 完成nan和inf的使用,与上课一致

In [1]:
import numpy as np

np.nan != np.nan

True

In [2]:
arr = np.random.rand(3, 4)
# 随机选择几个元素设为nan
num_nan = np.random.randint(1, 4)  # 随机设置1到3个nan
nan_indices = np.random.choice(arr.size, num_nan, replace=False)
arr.flat[nan_indices] = np.nan
print(arr)

[[0.51919347 0.05813032        nan 0.92920388]
 [0.96754282 0.28542406 0.37155266 0.05438053]
 [0.77801534        nan 0.63484527 0.21834751]]


In [3]:
np.isnan(arr)

array([[False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [4]:
arr != arr

array([[False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [8]:
arr = np.array([1, 0])
result = arr[0] / arr[1]
print(result)

inf


/var/folders/y0/bfxm66992x3f3164jm5lmndm0000gn/T/ipykernel_30865/2266480809.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  result = arr[0] / arr[1]


In [9]:
np.inf > -np.inf

True