### np二维数组转置练习，轴滚动练习

In [1]:
import numpy as np

# 创建一个二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("原数组：")
print(arr)

# 转置数组
arr_T = arr.T

print("转置后的数组：")
print(arr_T)

原数组：
[[1 2 3]
 [4 5 6]]
转置后的数组：
[[1 4]
 [2 5]
 [3 6]]


In [2]:
# 轴滚动练习
arr_rolled = np.roll(arr, 1, axis=0)
print("轴滚动后的数组：")
print(arr_rolled)

轴滚动后的数组：
[[4 5 6]
 [1 2 3]]
