### 掌握numpy的数据类型，练习数组和数的运算，数组和数组的运算，理解数组的轴

#### 数据类型

In [1]:
import numpy as np

# 获取所有numpy支持的数据类型
all_dtypes = np.sctypeDict

# 只保留不重复的dtype对应名称
unique_dtypes = set(np.sctypeDict.values())

# 打印所有可用的数据类型（dtype方式）
print("NumPy支持的数据类型（dtype）：")
for dtype in sorted(unique_dtypes, key=lambda x: str(x)):
    print(dtype)

NumPy支持的数据类型（dtype）：
<class 'numpy.bool'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.longdouble'>
<class 'numpy.longlong'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.ulonglong'>
<class 'numpy.void'>


#### 数组、数、轴

In [ ]:
# 创建一个 (3,4) 的 ndarray
arr = np.arange(12).reshape(3, 4)
print("原数组：\n", arr)

# 数组与数的运算: 每个元素+10
arr_plus_10 = arr + 10
print("每个元素加10后的数组：\n", arr_plus_10)

# 数组与数组的运算: 与自身相乘
arr_squared = arr * arr
print("数组与自身相乘：\n", arr_squared)

# 理解数组的轴
print("数组 shape:", arr.shape)
print("按 axis=0 求和：", np.sum(arr, axis=0))  # 列和
print("按 axis=1 求和：", np.sum(arr, axis=1))  # 行和

原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
每个元素加10后的数组：
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
数组与自身相乘：
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
数组 shape: (3, 4)
按 axis=0 求和： [12 15 18 21]
按 axis=1 求和： [ 6 22 38]
