### 完成数组的连接，堆叠

In [2]:
import numpy as np

# 随机生成两个数组
a = np.random.randint(0, 10, size=(2, 3))
b = np.random.randint(10, 20, size=(2, 3))

print("数组 a:\n", a)
print("数组 b:\n", b)

# 使用concatenate按行拼接（竖直方向, axis=0）
combined_v = np.concatenate((a, b), axis=0)
print("使用concatenate竖直方向拼接结果:\n", combined_v)

# 使用concatenate按列拼接（水平方向, axis=1）
combined_h = np.concatenate((a, b), axis=1)
print("使用concatenate水平方向拼接结果:\n", combined_h)

# 使用stack进行堆叠，增加一个新轴，例如axis=0
stacked = np.stack((a, b), axis=0)
print("使用stack堆叠结果（新轴在axis=0）:\n", stacked)

数组 a:
 [[7 3 1]
 [7 4 9]]
数组 b:
 [[12 15 12]
 [11 12 17]]
使用concatenate竖直方向拼接结果:
 [[ 7  3  1]
 [ 7  4  9]
 [12 15 12]
 [11 12 17]]
使用concatenate水平方向拼接结果:
 [[ 7  3  1 12 15 12]
 [ 7  4  9 11 12 17]]
使用stack堆叠结果（新轴在axis=0）:
 [[[ 7  3  1]
  [ 7  4  9]]

 [[12 15 12]
  [11 12 17]]]
