### 使用数组的索引和切片，掌握数组数值修改

In [3]:
import numpy as np

# 创建一个一维数组
arr = np.array([10, 20, 30, 40, 50])

# 通过索引访问数组元素
print("第一个元素:", arr[0])
print("最后一个元素:", arr[-1])

# 通过切片获取部分数组
print("前三个元素:", arr[:3])
print("从第三个到最后的元素:", arr[2:])

# 修改数组中的某个元素
arr[1] = 25
print("修改后的数组:", arr)

第一个元素: 10
最后一个元素: 50
前三个元素: [10 20 30]
从第三个到最后的元素: [30 40 50]
修改后的数组: [10 25 30 40 50]


In [4]:
# 创建一个二维数组
matrix = np.arange(16).reshape(4, 4)
print("原始数组：\n", matrix)

# 使用np.split对数组进行分块（这里将第1维按2分块，即每两行一块）
splitted = np.split(matrix, 2, axis=0)
print("分块后的数组：")
for i, block in enumerate(splitted):
    print(f"第{i+1}块:\n{block}")

原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
分块后的数组：
第1块:
[[0 1 2 3]
 [4 5 6 7]]
第2块:
[[ 8  9 10 11]
 [12 13 14 15]]
