In [6]:
import torch

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape

torch.Size([12])

In [8]:
x.numel()

12

In [9]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### 标准高斯分布（正态分布）中随机采样（3，4）形状的张量

In [12]:
torch.randn(3, 4)

tensor([[-0.9332,  0.4438,  0.6485, -0.8852],
        [ 0.6197,  1.1540,  1.3864, -0.4059],
        [ 0.4640,  0.5378, -1.4643,  0.0545]])

### 按元素做运算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### 按行-轴0，按列-轴1

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [19]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X.sum()

tensor(66.)

In [21]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [24]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4658574816
id(Z): 4658574816


In [26]:
before = id(X)
X += Y  # == "X [:] = X + Y"
id(X) == before

True

### 2.1.8 练习

In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

X, Y, X == Y, X < Y, X > Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [46]:
a = torch.arange(18).reshape((3, 3, 2))
b = torch.arange(6).reshape((1, 3, 2))
a, b, a + b

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15],
          [16, 17]]]),
 tensor([[[0, 1],
          [2, 3],
          [4, 5]]]),
 tensor([[[ 0,  2],
          [ 4,  6],
          [ 8, 10]],
 
         [[ 6,  8],
          [10, 12],
          [14, 16]],
 
         [[12, 14],
          [16, 18],
          [20, 22]]]))

In [47]:
a = torch.arange(12).reshape((4, 3, 1))
b = torch.arange(6).reshape((1, 3, 2))
a, b, a + b

(tensor([[[ 0],
          [ 1],
          [ 2]],
 
         [[ 3],
          [ 4],
          [ 5]],
 
         [[ 6],
          [ 7],
          [ 8]],
 
         [[ 9],
          [10],
          [11]]]),
 tensor([[[0, 1],
          [2, 3],
          [4, 5]]]),
 tensor([[[ 0,  1],
          [ 3,  4],
          [ 6,  7]],
 
         [[ 3,  4],
          [ 6,  7],
          [ 9, 10]],
 
         [[ 6,  7],
          [ 9, 10],
          [12, 13]],
 
         [[ 9, 10],
          [12, 13],
          [15, 16]]]))