In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [3]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [4]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [5]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [6]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [7]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

### 求和降维

In [8]:
print(A.shape)
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0.shape)
A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1.shape)

A_sum_axis0, A_sum_axis1

torch.Size([5, 4])
torch.Size([4])
torch.Size([5])


(tensor([40., 45., 50., 55.]), tensor([ 6., 22., 38., 54., 70.]))

In [9]:
A.sum(), A.sum(axis=[0, 1])

(tensor(190.), tensor(190.))

In [10]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [11]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0], A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]), 5)

In [12]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [13]:
A / sum_A # 广播+除法

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [14]:
# axis=0：沿着“行方向”往下加，也就是每一列从上到下累加
# axis=1：沿着“列方向”往右加，也就是每一行从左到右累加
A, A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.],
         [12., 25., 39., 54.],
         [16., 33., 51., 70.]]))

In [15]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y), torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

### 矩阵-向量积

In [16]:
A, x, A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

### 矩阵-矩阵乘法

In [17]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 范数

In [18]:
# L2 范数是向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))

# L1 范数表示为向量元素的绝对值之和
print(torch.abs(u).sum())

tensor(5.)
tensor(7.)


In [19]:
# Forbenius 范数
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [20]:
A, A.T, A == (A.T).T

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  4.,  8., 12., 16.],
         [ 1.,  5.,  9., 13., 17.],
         [ 2.,  6., 10., 14., 18.],
         [ 3.,  7., 11., 15., 19.]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [21]:
B = torch.ones(5, 4)
A, B, A + B, A.T + B.T, (A + B).T == (A.T + B.T)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.]]),
 tensor([[ 1.,  5.,  9., 13., 17.],
         [ 2.,  6., 10., 14., 18.],
         [ 3.,  7., 11., 15., 19.],
         [ 4.,  8., 12., 16., 20.]]),
 tensor([[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]))

In [22]:
A = torch.randint(low=0, high=10, size=(5, 5), dtype=torch.int32)
A, A + A.T

(tensor([[4, 8, 1, 6, 9],
         [9, 2, 4, 1, 1],
         [8, 2, 7, 4, 8],
         [9, 0, 1, 0, 3],
         [3, 5, 1, 7, 1]], dtype=torch.int32),
 tensor([[ 8, 17,  9, 15, 12],
         [17,  4,  6,  1,  6],
         [ 9,  6, 14,  5,  9],
         [15,  1,  5,  0, 10],
         [12,  6,  9, 10,  2]], dtype=torch.int32))

In [23]:
A = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
A, len(A)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 2)

In [26]:
A = A.reshape(1, 2, 12)
A, len(A)

(tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]]]),
 1)

In [27]:
A = A.reshape(2, 2, 6)
A, len(A)

(tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.]]]),
 2)

In [28]:
A = A.reshape(3, 8)
A, len(A)

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20., 21., 22., 23.]]),
 3)

In [31]:
A.sum(axis=0), A.sum(axis=1)

(tensor([24., 27., 30., 33., 36., 39., 42., 45.]), tensor([ 28.,  92., 156.]))

In [32]:
A / A.sum(axis=0)

tensor([[0.0000, 0.0370, 0.0667, 0.0909, 0.1111, 0.1282, 0.1429, 0.1556],
        [0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333],
        [0.6667, 0.6296, 0.6000, 0.5758, 0.5556, 0.5385, 0.5238, 0.5111]])

In [33]:
A / A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.0357, 0.0714, 0.1071, 0.1429, 0.1786, 0.2143, 0.2500],
        [0.0870, 0.0978, 0.1087, 0.1196, 0.1304, 0.1413, 0.1522, 0.1630],
        [0.1026, 0.1090, 0.1154, 0.1218, 0.1282, 0.1346, 0.1410, 0.1474]])

In [37]:
A = A.reshape(2, 3, 4)
A, (A.sum(axis=0)).shape, (A.sum(axis=1)).shape, (A.sum(axis=2)).shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 torch.Size([3, 4]),
 torch.Size([2, 4]),
 torch.Size([2, 3]))

In [39]:
A = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
norm_default = torch.linalg.norm(A)
norm_axis0 = torch.linalg.norm(A, dim=0)
norm_axis1 = torch.linalg.norm(A, dim=1)
norm_axis2 = torch.linalg.norm(A, dim=2)
norm_keepdims = torch.linalg.norm(A, dim=(1,2), keepdim=True)
norm_multiple_axes = torch.linalg.norm(A, dim=(0, 2))
(norm_default, norm_axis0.shape, norm_axis1.shape, norm_axis2.shape, norm_keepdims.shape, norm_multiple_axes.shape)

(tensor(65.7571),
 torch.Size([3, 4]),
 torch.Size([2, 4]),
 torch.Size([2, 3]),
 torch.Size([2, 1, 1]),
 torch.Size([3]))

In [41]:
# 对任意形状张量进行norm函数测试
B = torch.arange(18, dtype=torch.float32).reshape(3, 2, 3)
# 按默认设置（所有元素范数）
norm_all = torch.linalg.norm(B)
# 沿第0轴计算范数
norm_dim0 = torch.linalg.norm(B, dim=0)
# 沿第1和2轴计算范数，保持维度
norm_dim12 = torch.linalg.norm(B, dim=(1,2), keepdim=True)
# 沿第2轴计算范数，不保持维度
norm_dim2 = torch.linalg.norm(B, dim=2)
(norm_all, norm_dim0, norm_dim0.shape, norm_dim12.shape, norm_dim2.shape)

(tensor(42.2493),
 tensor([[13.4164, 14.7986, 16.2481],
         [17.7482, 19.2873, 20.8567]]),
 torch.Size([2, 3]),
 torch.Size([3, 1, 1]),
 torch.Size([3, 2]))